services:
  web:
    container_name: web
    build:
      context: ./web
    ports:
      - ${HTTP_PUBLISHED_PORT:-80}:80
      - ${HTTPS_PUBLISHED_PORT:-443}:443
    volumes:
      - ./web/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./web/logs:/var/log/httpd
      - ./web/conf.d:/etc/httpd/conf.d
      - ./web/startup.sh:/startup.sh
      - ./cert/server.crt:/etc/pki/tls/certs/localhost.crt
      - ./cert/server.key:/etc/pki/tls/private/localhost.key
      - ${HOME_DIR:-G:\MUS\home}:/home
      - ${HTML_DIR:-G:\MUS\var\www\html}:/var/www/html
      - ${SMARTY_DIR:-G:\MUS\usr\lib64\php\pear\smarty}:/usr/lib64/php/pear/smarty
      - ${SHAREPHP_DIR:-G:\MUS\usr\share\php}:/usr/share/php
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - app
      - db

  app:
    container_name: app
    build:
      context: ./app
    volumes:
      - ./app/php.ini:/usr/local/etc/php/php.ini
      - ./app/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ${HOME_DIR:-G:\MUS\home}:/home
      - ${HTML_DIR:-G:\MUS\var\www\html}:/var/www/html
      - ${SMARTY_DIR:-G:\MUS\usr\lib64\php\pear\smarty}:/usr/lib64/php/pear/smarty
      - ${SHAREPHP_DIR:-G:\MUS\usr\share\php}:/usr/share/php
    environment:
      TZ: Asia/Tokyo

  db:
    image: postgres:13.11-alpine
    container_name: db
    ports:
      - ${POSTGRES_PUBLISHED_PORT:-5432}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-adminmin}
      TZ: Asia/Tokyo

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - ${PGADMIN_PUBLISHED_PORT:-8080}:80
    volumes:
      - ./pgadmin4-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-demo.digicon@topcreation.co.jp}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASS:-adminmin}
      TZ: Asia/Tokyo
    depends_on:
      - db

  ftpsrv:
    image: stilliard/pure-ftpd
    container_name: ftpsrv
    ports:
      - ${FTP_CTRL_PORT:-21}:21
      - ${FTP_PASV_MIN_PORT:-50000}-${FTP_PASV_MAX_PORT:-50009}:${FTP_PASV_MIN_PORT:-50000}-${FTP_PASV_MAX_PORT:-50009}
    volumes: 
      - ./ftp/data:${FTP_USER_HOME:-/home/ftpuser}
      - ./ftp/passwd:/etc/pure-ftpd/passwd
      - ./ftp/log:/var/log/pure-ftpd/
      - ./cert:/etc/ssl/private
    environment:
      PUBLICHOST: ftpsrv
      FTP_USER_NAME: ${FTP_USER_NAME:-ftpuser}
      FTP_USER_PASS: ${FTP_USER_PASS:-adminmin}
      FTP_USER_HOME: /home/${FTP_USER_NAME:-ftpuser}
      FTP_PASSIVE_PORTS: ${FTP_PASV_MIN_PORT:-50000}:${FTP_PASV_MAX_PORT:-50009}
      ADDED_FLAGS: -O w3c:/var/log/pure-ftpd/transfer.log --tls 1
      TLS_CN: localhost
      TLS_ORG: TopCreation
      TLS_C: JP
      TZ: Asia/Tokyo

  sftpsrv:
    image: atmoz/sftp
    container_name: sftpsrv
    volumes:
      - ./sftp:/home/${SFTP_USER_NAME:-sftpuser}
    ports:
      - ${SFTP_PUBLISHED_PORT:-22}:22
    command: ${SFTP_USER_NAME:-sftpuser}:${SFTP_USER_PASS:-adminmin}:1001
    environment:
      TZ: Asia/Tokyo

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - target: 8025
        published: ${MAILPIT_PUBLISHED_PORT:-8025}
        protocol: tcp
        mode: host
    volumes:
      - ./mailpit-data:/tmp
    environment:
      MP_DATA_FILE: /tmp/mailpit.db
      TZ: Asia/Tokyo
